// Define an array of sentences
const sentences = [
    "A song about rediscovering hope after hitting rock bottom",
"A tribute to the unsung heroes of everyday life",
"An exploration of the complexities of human connection in the digital age",
"A reflection on the passage of time and the inevitability of change",
"A celebration of the beauty and resilience of nature",
"A meditation on the meaning of success and fulfillment",
"A journey through the highs and lows of a tumultuous relationship",
"A protest anthem against social injustice and inequality",
"A nostalgic ode to childhood innocence and wonder",
"A portrait of a small town and its inhabitants, each with their own stories to tell",
"A whimsical tale of adventure and discovery",
"An exploration of identity and self-acceptance",
"A love letter to the magic of music and its ability to transcend barriers",
"A soul-searching ballad about finding one's purpose in life",
"A haunting lament for the ones we've lost along the way",
"A rallying cry for unity and solidarity in a divided world",
"An exploration of dreams and their power to inspire and motivate",
"A cautionary tale about the dangers of unchecked ambition",
"A reflection on the fleeting nature of fame and fortune",
"A celebration of individuality and the beauty of being true to oneself",
"A song inspired by a work of art or piece of literature",
"An anthem for the underdogs and outsiders, fighting against the odds",
"A reminder to cherish the present moment and live life to the fullest",
"A meditation on the nature of love and its ability to heal and transform",
"A tribute to the resilience of the human spirit in the face of adversity",
"A reflection on the impact of technology on our lives and relationships",
"A bittersweet farewell to a chapter of life that's come to an end",
"An exploration of the mysteries of the universe and our place within it",
"A celebration of cultural diversity and the richness it brings to our world",
"A song inspired by a vivid dream or recurring nightmare",
"A reflection on the passage of time and the lessons learned along the way",
"An ode to the power of friendship and the bonds that tie us together",
"A meditation on the beauty of impermanence and the fleeting nature of life",
"A tribute to the power of resilience and the ability to bounce back from adversity",
"A reflection on the cyclical nature of history and the lessons we can learn from the past",
"A celebration of the simple pleasures of everyday life",
"An exploration of the human condition and the universal experiences that connect us all",
"A song inspired by a specific place or landscape that holds special meaning",
"A reminder to embrace vulnerability and the messy, imperfect parts of ourselves",
"An exploration of the concept of home and what it means to belong",
"A reflection on the beauty of aging and the wisdom that comes with experience",
"A meditation on the interconnectedness of all living things",
"A song inspired by a personal struggle or triumph",
"An exploration of the intersection between art and politics",
"A celebration of resilience and the ability to rise above life's challenges",
"A reflection on the impact of human activity on the environment",
"A tribute to the power of creativity and the role it plays in shaping our world",
"A meditation on the fleeting nature of happiness and the pursuit of contentment",
"A song inspired by a historical event or figure",
"An exploration of the concept of fate and the role it plays in shaping our lives",
"A celebration of the power of community and collective action",
"A reflection on the complexities of love and the ways it can both lift us up and tear us apart",
"An exploration of the connection between body, mind, and spirit",
"A tribute to the power of resilience and the human capacity for survival",
"A meditation on the beauty of solitude and the importance of self-reflection",
"A reflection on the power of forgiveness and the healing it can bring",
"A celebration of the power of imagination and the worlds it can create",
"An exploration of the concept of justice and its role in creating a fairer world",
"A meditation on the nature of memory and its ability to shape our identity",
"A tribute to the power of storytelling and its ability to connect us across time and space",
"A reflection on the passage of time and the inevitability of mortality",
"An exploration of the concept of freedom and the sacrifices made to achieve it",
"A celebration of the beauty of the natural world and our responsibility to protect it",
"A meditation on the power of music to evoke emotion and transcend language",
"A reflection on the complexities of human relationships and the bonds that tie us together",
"A tribute to the power of resilience and the human capacity to overcome adversity",
"An exploration of the concept of truth and the search for meaning in an uncertain world",
"A celebration of the power of perseverance and the ability to keep going in the face of obstacles",
"A meditation on the concept of destiny and the role it plays in shaping our lives",
"A reflection on the beauty of imperfection and the acceptance of our flaws",
"An exploration of the concept of faith and its role in guiding our lives",
"A celebration of the power of love to transcend boundaries and unite us all",
"A meditation on the nature of beauty and its ability to inspire and uplift",
"A reflection on the power of empathy and the importance of understanding one another",
"A tribute to the power of resilience and the human capacity for adaptation",
"An exploration of the concept of courage and the ability to face our fears",
"A celebration of the power of art to change hearts and minds",
"A meditation on the concept of time and its impact on our lives",
"A reflection on the beauty of diversity and the richness it brings to our world",
"A tribute to the power of community and the strength we find in coming together",
"An exploration of the concept of redemption and the possibility of second chances",
"A celebration of the power of kindness and the ripple effect it can create",
"A meditation on the concept of legacy and the mark we leave on the world",
"A reflection on the power of resilience and the ability to bounce back from adversity",
"A tribute to the power of friendship and the bonds that sustain us through life's ups and downs",
"An exploration of the concept of freedom and the sacrifices made to achieve it",
"A celebration of the power of resilience and the human capacity to overcome adversity",
"A meditation on the concept of truth and the search"
];

// Function to generate a random sentence
function generateRandomSentence() {
    const randomIndex = Math.floor(Math.random() * sentences.length);
    document.getElementById('sentence').innerText = sentences[randomIndex];
}

// Add event listener to the button
document.getElementById('generateButton').addEventListener('click', generateRandomSentence);